#!/bin/bash

###
##  puppet-lint.sh :: run puppet-lint in jenkins
#

LINT="/var/lib/gems/1.8/bin/puppet-lint"

find $1 -iname "*pp" | while read file; do
  _TMP=$(mktemp -p /tmp/ puppet-lint.XXXX)
  echo "# puppet-lint ${file}"
  ${LINT} ${file} > ${_TMP}
  
  _WARN=$(grep ^WARNING ${_TMP} | wc -l)
  _ERR=$(grep ^ERROR ${_TMP} | wc -l)

  if [ ${_WARN} -ge 1 ]; then
    echo "Warnings from puppet-lint for ${file}:"
    grep ^WARNING ${_TMP}
  fi

  if [ ${_ERR} -ge 1 ]; then
    echo "Errors from puppet-lint for ${file}"
    grep ^ERROR ${_TMP}
  fi 

  rm ${_TMP}
  test ${_ERR} -ge 1 && exit 1
done
